name: mp_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main/
  - https://repo.anaconda.com/pkgs/r/
  - https://repo.anaconda.com/pkgs/msys2/
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pip=25.3=pyhc872135_0
  - powershell_shortcut=0.0.1=haa95532_4
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.4.0
      - cffi==2.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mediapipe==0.10.32
      - numpy==2.2.6
      - opencv-contrib-python==4.13.0.90
      - opencv-python==4.13.0.90
      - pillow==12.1.0
      - pycparser==3.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - sounddevice==0.5.5
prefix: C:\Users\cheng\anaconda3\envs\mp_env
